### PR TITLE
Little rework of html expansion

### PR DESCRIPTION
**Pull request by r-stein**
This pull request does
- improve tolerance (e.g. for unmatching tags)
- comments are now ignored when searching tags
- added a step in between, when expanding from inside a tag, which is the only behavior change. This selects the tag header before selecting the whole body.

### CODE REVIEW

**Comment by aronwoost** [comment]
Interesting. Can you provide an updated animated gif for HTML (to explain the changes and for the README)?

**Comment by r-stein** [comment]
This only slighly changes the behavior and mostly adds "if result is found" checks to avoid errors and ignores comment-tags when searching for the sourrounding tags.
The only real behavior change is, that it adds a step in between for the "expand to matching tag":

| before | after |
| --- | --- |
| expand_html_tag_old | expand_html_tag_new |

**Comment by aronwoost** [comment]
Cool. And that also fixes #48, right?

**Comment by r-stein** [comment]
I does not fix it yet, but it requires only little changes and I will implement it.

**Comment by r-stein** [comment]
It is supported now:
expand_html_tag_inside
It might also be useful to expand to the attribute, i.e. `href="#"` in the example. But not in this pull request =).

**Comment by aronwoost** [comment]
Like I wrote in #48 I'm still having trouble to find the usefulness of this feature. Expand to attribute I'd find cool. For expanding to tag-content (w/o `<>`) or tag (with `<>`) I am unsure how this make sense (except for self closing tags).

Or am I misunderstanding it?

**Comment by r-stein** [comment]
At least in my opinion it feels unexpected and to much if expands to the tag with body before expanding to the tag (just `<>`).

I currently don't use html/xml that much and hence I don't have a good real world example. However I can imagine someone updating a html tag and wants to update some other tags with the same content:

expand_html_why_tag_body_example

Or wants to reuse the tag head without copying the body:
expand_html_why_tag_head_example

**Pull request merged**
