### PR TITLE
LaTeX Support

### PR DESCRIPTION
**Pull request by r-stein**
Support for LaTeX:

expand_region_latex_v2

*Edit: Updated demo image*

### CODE REVIEW

**Comment by aronwoost** [comment]
Awesome stuff! Do you think we should squash those commits? Or are they independently informative enough to keep them?

**Comment by r-stein** [comment]
No we don't need to keep the commits and you can squash it into one commit.

**Comment by aronwoost** [comment]
If you want to keep being the commit author, you'll need to do that. :wink: :+1:

**Comment by r-stein** [comment]
done =)

**Pull request merged**
