### PR TITLE
Force Soft-Undo integration

### PR DESCRIPTION
**Pull request by r-stein**
This pull request forces the entry in the soft-undo history based on the suggestion of @bizoo in https://github.com/aronwoost/sublime-expand-region/issues/39. This will also add multi-cursor undo support as suggested in  https://github.com/aronwoost/sublime-expand-region/issues/40.

Beside from the multi-cursor support the other advantage is the continuation of soft-undo before the first expansion (currently you can only soft-undo until the first `expand_region`-call).

Since ST3 should integrate into soft-undo without doing something special, this code is hacky and just calls api methods to enforce the entry in the soft-undo history. Hence I would implement it as opt-out and add a setting to disable it. However it should be tested all OS/ST combinations to ensure it works for everyone.

Tested on

- [x] Windows ST3
- [x] Windows ST2
- [x] Linux ST3
- [x] Linux ST2
- [x] OSX ST3
- [x] OSX ST2

This is a suggestion to discuss whether to add this or not / add it as opt-in or opt-out.

### CODE REVIEW

**Comment by aronwoost** [comment]
Works on OSX!

**Comment by aronwoost** [comment]
I don't fully understand what the issue is with ST3. Why is it hacky?

**Comment by r-stein** [comment]
The whole thing is kind of hacky. The idea is to end the current edit and start a new different one to enforce ST to insert a separate soft-undo entry. This is not officially supported and kind of hacky to establish. I implemented it via "try-and-error" to get the shortest working code. ST3 needs to reinsert the regions in the new edit (otherwise the soft-undo does not work properly). ST2 prints a warning, because the edit is closed twice.

**Comment by excetara2** [comment]
This is great and not sure why it was never merged.

**Comment by r-stein** [comment]
@excetara2 I will merge it this weekend

**Pull request merged**
