### PR TITLE
Cooperate with BracketHighlighter

### PR DESCRIPTION
**Pull request by r-stein**
BracketHighlighter recently added a way to extract the bracket locations from the view. Therefore we can use that information to make the expansion way smarter with very little work.

This PR extracts the BH brackets and our expansions. They are joined to get the "better"/closer one.

Example (`#ifdef` is defined by BracketHighligher):
bh_example

### CODE REVIEW

**Comment by aronwoost** [comment]
Cool!

**Comment by r-stein** [comment]
I have created a `develop` branch so I can merge this and use it in the meta-interpreter PR without messing with the github history. In addition we can use the branch for pre-releases [`install_prereleases`](https://packagecontrol.io/docs/settings).

**Comment by r-stein** [comment]
If you are ok with it I will create a "release candidate" prerelease `v1.5.0-rc.0` for this feature and write a little info on how to enable prereleases to the readme.

**Comment by aronwoost** [comment]
👍

**Comment by r-stein** [comment]
Since there were no complaints and I didn't have any issue I will create a release for the prerelease.

**Pull request merged**
